/*
 * กรมการปกครอง / ตรวจสอบข้อมูลโดยใช้ข้อมูลบนบัตรฯ และเลขหลังบัตร
 *
 * หน่วยงานสามารถยืนยันตัวบุคคลโดยใช้ข้อมูลจากบัตรประชาชน และเลขหลังบัตร ผ่าน Government API ที่ สรอ. จัดเตรียมไว้ให้ ดังนี้
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DopaError struct {
	// บัตรสิ้นสภาพการใช้งาน เนื่องจากกรณีบัตรหาย
	Message string `json:"message,omitempty"`
}
